version: '3.8'

services:
  kaggle-notebook:
    image: gcr.io/kaggle-images/python:latest
    container_name: kaggle-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    env_file:
      - .env
    working_dir: /home/jovyan/work
    command: jupyter lab --NotebookApp.token='' --NotebookApp.password='' --ip=0.0.0.0 --port=8888 --allow-root --no-browser
    stdin_open: true
    tty: true

