version: '3.8'

services:
  kaggle-notebook:
    image: gcr.io/kaggle-images/python:latest
    container_name: kaggle-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME:-your_username}
      - KAGGLE_KEY=${KAGGLE_KEY:-your_api_key}
      - JUPYTER_ENABLE_LAB=yes
    command: start.sh jupyter lab --NotebookApp.token='' --NotebookApp.password='' --ip=0.0.0.0 --port=8888
    stdin_open: true
    tty: true

